### ISSUE TITLE
The screen locked while video is playing

### ISSUE THREAD

**Issue by MuggleLego** [iosmanthus/nixos-config#1]
**To Reproduce**
Open whatever video and enjoy it for more than your betterLockScreen service inactive interval.

**Expected Behavior**
The screen locked when the computer is truly inactive.

**Comment by iosmanthus** [comment]
You could add `-corner` to https://nix-community.github.io/home-manager/options.html#opt-services.screen-locker.xautolock.extraOptions. While you are watching videos, move the cursor to the corner you specified, the screen won't get locked.
